In [1]:
import numpy as np
a = np.arange(30,18,-1).reshape(3,4)  #降序 
print(a)
print(np.cumsum(a)) #后一个数和前面的数分别累加

print(np.sum(a,axis=0))  # 对列进行求和计算

print(np.sum(a,axis=1)) # 对行进行计算


print(np.diff(a))  #累减
print(np.nonzero(a))
print(np.sort(a)) #排序了 
print(np.transpose(a))   

print((a.T).dot(a))  #@转置*原矩阵
print(np.clip(a,20,25))  #大于25的数变成25，小于20的数变成20
 

[[30 29 28 27]
 [26 25 24 23]
 [22 21 20 19]]
[ 30  59  87 114 140 165 189 212 234 255 275 294]
[78 75 72 69]
[114  98  82]
[[-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]]
(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2], dtype=int64), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3], dtype=int64))
[[27 28 29 30]
 [23 24 25 26]
 [19 20 21 22]]
[[30 26 22]
 [29 25 21]
 [28 24 20]
 [27 23 19]]
[[2060 1982 1904 1826]
 [1982 1907 1832 1757]
 [1904 1832 1760 1688]
 [1826 1757 1688 1619]]
[[25 25 25 25]
 [25 25 24 23]
 [22 21 20 20]]


In [30]:
import numpy as np
a = np.arange(3,15).reshape(3,4)  #产生三行四列的矩阵 从3到15
print(a[2]) #索引 

print(a[2][1])
print(a[:,1]) #打印第1列  
print(a[2,:])  #打印第二行

for row in a:
    print(row)
for column in a:
    print(column)
    

print(a.flatten())

for item in a.flat:   #把三行四列  变成一行输出
    print(item)


[11 12 13 14]
12
[ 4  8 12]
[11 12 13 14]
[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]
[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]
[ 3  4  5  6  7  8  9 10 11 12 13 14]
3
4
5
6
7
8
9
10
11
12
13
14


In [39]:
import numpy as np
a = np.array([1,5,9])
b = np.array([2,5,7])
print(a.shape,d.shape,c.shape)  #行数或列数
c= np.vstack((a,b)) #垂直合并数组
d = np.hstack((a,b))#水平合并数组


print(c)
print("-------------")
print(d)



(3,) (6,) (2, 3)
[[1 5 9]
 [2 5 7]]
-------------
[1 5 9 2 5 7]


In [50]:
import numpy as np
a = np.arange(30,14,-1).reshape(4,4)  #降序  30到14 一共16 个数 四行四列 
print(a)
print(np.split(a,2,axis = 1))  # 只能进行相等的块分割  竖向分割
print(np.split(a,2,axis = 0))  #横向分割  即分割行或列必须为偶数  如果是三行就不能进行行分裂
"""
进行不等项的分割
"""

print(np.array_split(a,3,axis = 1)) 
"""3表示将矩阵竖向的分成三部分 
                                     分别为2,1,1列"""




[[30 29 28 27]
 [26 25 24 23]
 [22 21 20 19]
 [18 17 16 15]]
[array([[30, 29],
       [26, 25],
       [22, 21],
       [18, 17]]), array([[28, 27],
       [24, 23],
       [20, 19],
       [16, 15]])]
[array([[30, 29, 28, 27],
       [26, 25, 24, 23]]), array([[22, 21, 20, 19],
       [18, 17, 16, 15]])]
[array([[30, 29],
       [26, 25],
       [22, 21],
       [18, 17]]), array([[28],
       [24],
       [20],
       [16]]), array([[27],
       [23],
       [19],
       [15]])]


'3表示将矩阵竖向的分成三部分 \n                                     分别为2,1,1列'

In [60]:
"""   """
import numpy as np
a = np.arange(4)
print(a[3])
b= a.copy()
b
a

3


array([0, 1, 2, 3])

In [3]:
#pandas numpy 主要用于矩阵运算 
import numpy as np
import pandas as pd
s = pd.Series([1,2,3,4,5,6,np.nan]) 
print(s)

dates = pd.date_range('20181103',periods = 10)
print(dates)

df = pd.DataFrame(np.random.randn(10,5),index = dates,columns = ['罗梦玲','张三','李四','曾玉健','蒋琰'])  #类似于二维数组的索引，数据是numpy的数据
df  #6,4 表示 6行4列的随机数  invalid character in identifier  可能是中文的字符输入了



0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
5    6.0
6    NaN
dtype: float64
DatetimeIndex(['2018-11-03', '2018-11-04', '2018-11-05', '2018-11-06',
               '2018-11-07', '2018-11-08', '2018-11-09', '2018-11-10',
               '2018-11-11', '2018-11-12'],
              dtype='datetime64[ns]', freq='D')


罗梦玲        张三        李四       曾玉健        蒋琰
2018-11-03  0.025900  1.349874  1.269981 -0.540395  0.494808
2018-11-04  0.160948 -1.226662 -0.974195 -1.757333  1.432829
2018-11-05 -0.280794  0.534628 -0.053796  0.732671 -0.147732
2018-11-06 -1.360364 -1.994799 -0.707849  0.612152  0.416700
2018-11-07 -0.769379  0.435936 -1.202058 -0.302451  0.854562
2018-11-08 -0.217994 -1.071270 -0.347959 -0.565472 -2.616613
2018-11-09  1.207911 -0.170187 -0.915282  1.681036 -0.231447
2018-11-10  0.891080 -0.227958 -1.256034 -0.632186 -1.242976
2018-11-11  0.021669  2.026763 -0.707089 -2.524777  1.095094
2018-11-12 -0.425046 -1.463079  1.076972  0.294003 -1.164787

In [7]:
import pandas as pd
import numpy as np
dates = pd.date_range('20181108',periods = 6)   #下面的reshape都两层括号请注意
df = pd.DataFrame(np.arange(24).reshape((6,4)),index = dates,columns = ['A','B','C','D'])
print(df['A'],df.A)



2018-11-08     0
2018-11-09     4
2018-11-10     8
2018-11-11    12
2018-11-12    16
2018-11-13    20
Freq: D, Name: A, dtype: int32 2018-11-08     0
2018-11-09     4
2018-11-10     8
2018-11-11    12
2018-11-12    16
2018-11-13    20
Freq: D, Name: A, dtype: int32
