In [2]:
import numpy as np

a=np.matrix([[1,1],[1,0]])

a^100


matrix([[101, 101],
        [101, 100]], dtype=int32)

In [31]:
d

matrix([[1, 1],
        [1, 0]], dtype=int32)

In [7]:
c

array([[2, 1],
       [1, 1]])

In [39]:
b

array([[1, 1],
       [1, 0]])

In [42]:
import time


def multi(a,b):
    c=[[0,0],[0,0]]
    for i in range(2):
        for j in range(2):
            for k in range(2):
                c[i][j]=c[i][j]+a[i][k]*b[k][j]
    return c


def matrix(n):
    base=[[1,1],[1,0]]
    ans=[[1,0],[0,1]]
    while n:
        if n&1:
            ans=multi(ans,base)
        base=multi(base,base)
        n>>=1
    # for i in range(2):
    #     print(ans[i])
    return ans[0][1]

def normal(n):
    a,b,c=0,1,1
    while n:
        a,b,c=b,c,b+c
        n-=1
    return a

n=int(input(">>>"))
start=time.time()
print("Normal:",normal(n))
print("use:",time.time()-start)
start=time.time()
print("Matrix:",matrix(n))
print("use:",time.time()-start)


>>>2
Normal: 1
use: 0.004975318908691406
Matrix: 1
use: 0.0
